### ISSUE TITLE
Uncaught TypeError TypeError: core is not a function

### ISSUE THREAD

**Issue by RiggerJay** [githubjonas/react-tiny-bbcode#18]
I am getting the following error when using this code 

And not sure how to fix  

Uncaught TypeError TypeError: core is not a function
    at toHTML (d:\dev\git\brimstone-FFHC-react\node_modules\@bbob\html\dist\index.js:55:1)
    at <anonymous> (d:\dev\git\brimstone-FFHC-react\src\FFHC\Event.js:27:1)
    at Event (d:\dev\git\brimstone-FFHC-react\src\FFHC\Event.js:20:1)
    at renderWithHooks (d:\dev\git\brimstone-FFHC-react\node_modules\react-dom\cjs\react-dom.development.js:16305:1)
    at mountIndeterminateComponent (d:\dev\git\brimstone-FFHC-react\node_modules\react-dom\cjs\react-dom.development.js:20074:1)
    at beginWork (d:\dev\git\brimstone-FFHC-react\node_modules\react-dom\cjs\react-dom.development.js:21587:1)
    at callCallback (d:\dev\git\brimstone-FFHC-react\node_modules\react-dom\cjs\react-dom.development.js:4164:1)
    at invokeGuardedCallbackDev (d:\dev\git\brimstone-FFHC-react\node_modules\react-dom\cjs\react-dom.development.js:4213:1)
    at invokeGuardedCallback (d:\dev\git\brimstone-FFHC-react\node_modules\react-dom\cjs\react-dom.development.js:4277:1)
    at beginWork$1 (d:\dev\git\brimstone-FFHC-react\node_modules\react-dom\cjs\react-dom.development.js:27451:1)
    at performUnitOfWork (d:\dev\git\brimstone-FFHC-react\node_modules\react-dom\cjs\react-dom.development.js:26557:1)
    at workLoopSync (d:\dev\git\brimstone-FFHC-react\node_modules\react-dom\cjs\react-dom.development.js:26466:1)
    at renderRootSync (d:\dev\git\brimstone-FFHC-react\node_modules\react-dom\cjs\react-dom.development.js:26434:1)
    at performSyncWorkOnRoot (d:\dev\git\brimstone-FFHC-react\node_modules\react-dom\cjs\react-dom.development.js:26085:1)
    at flushSyncCallbacks (d:\dev\git\brimstone-FFHC-react\node_modules\react-dom\cjs\react-dom.development.js:12042:1)
    at <anonymous> (d:\dev\git\brimstone-FFHC-react\node_modules\react-dom\cjs\react-dom.development.js:25651:1)

packages.json excerpt 
    "@bbob/html": "^3.0.2",
    "@bbob/preset-html5": "^3.0.2",
    "@bbob/core": "^3.0.2",
    "@emotion/react": "^11.11.4",
    "react": "^18.2.0",

```
import bbobHTML from '@bbob/html'
import presetHTML5 from '@bbob/preset-html5'


         <ul>
                {roadEncounters.events.map(function (event) {
                    return (
                        <li key={event.roll}>
                            <h1>{event.name}</h1>
                            <p>{event.flavor}</p>
                            <hr />
                            <p>{bbobHTML(event.details, presetHTML5()) }</p>
                        </li>
                    )
                })}
            </ul>
```

**Comment by RiggerJay** [comment]
wrong repo
